# Generated by Django 6.0.5 on 2026-05-22 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('document_type', models.CharField(choices=[('invoice_pdf', 'Invoice PDF'), ('bank_statement_csv', 'Bank Statement CSV')], max_length=32)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=16)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='documents.document')),
            ],
            options={
                'ordering': ['transaction_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity', models.CharField(blank=True, max_length=64, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='documents.document')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user', 'status'], name='documents_d_user_id_200c84_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['vendor'], name='documents_d_vendor_5f7666_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_date'], name='documents_d_documen_0eb394_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['currency'], name='documents_d_currenc_1d7705_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'),
        ),
    ]
